version: "3"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    privileged: true

  cassandra:
    image: "cassandra:3.11.9"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
  mongo:
    image: mongo:4.0
#    restart: on-failure
    ports:
      - 27017:27017
    privileged: true